version: "3.9"

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: new_root_password
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      - ./db/conf:/etc/mysql/conf.d
